export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN_TENANT: "ADMIN_TENANT",
  MANAGER: "MANAGER",
  EMPLOYEE: "EMPLOYEE",
  CLIENT: "CLIENT"
};

export const LEGACY_ROLE_MAP = {
  superadmin: ROLES.SUPER_ADMIN,
  admin: ROLES.ADMIN_TENANT,
  manager: ROLES.MANAGER
};

export const normalizeRole = (role) => LEGACY_ROLE_MAP[role] || role;

export const MODULE_PERMISSIONS = {
  dashboard: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT, ROLES.MANAGER],
  tenants: [ROLES.SUPER_ADMIN],
  users: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT],
  products: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT, ROLES.MANAGER],
  orders: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT, ROLES.MANAGER, ROLES.EMPLOYEE],
  customers: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT, ROLES.MANAGER],
  stocks: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT, ROLES.MANAGER, ROLES.EMPLOYEE],
  promotions: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT, ROLES.MANAGER],
  sales: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT, ROLES.MANAGER, ROLES.EMPLOYEE],
  billing: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT],
  reports: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT, ROLES.MANAGER],
  settings: [ROLES.SUPER_ADMIN, ROLES.ADMIN_TENANT]
};

export const DEFAULT_ENABLED_MODULES = ["dashboard", "users", "products", "orders", "customers", "stocks", "promotions", "sales", "reports", "settings"];
