import dotenv from "dotenv";
import connectDB from "./config/db.js";
import Perfume from "./models/Perfume.js";

dotenv.config();
await connectDB();

const samples = [
  {
    name: "Sauvage Eau de Toilette",
    brand: "Dior",
    description: "Un masculin frais, citrus et boise, inspire par les grands espaces et pense pour une signature quotidienne tres reconnaissable.",
    purchasePrice: 680,
    quantityPurchased: 16,
    price: 990,
    oldPrice: 1150,
    volume: "100ml",
    category: "Aromatique",
    gender: "Homme",
    stock: 11,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1200&q=90",
    notes: { top: "Bergamote, agrumes", middle: "Poivre, lavande", base: "Ambroxan, cedre, notes boisees" },
    isFeatured: true
  },
  {
    name: "Bleu de Chanel Eau de Parfum",
    brand: "Chanel",
    description: "Un boise aromatique elegant, frais et profond, parfait pour une clientele qui cherche une allure moderne et sobre.",
    purchasePrice: 760,
    quantityPurchased: 12,
    price: 1190,
    oldPrice: 1320,
    volume: "100ml",
    category: "Boise",
    gender: "Homme",
    stock: 8,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1619994403073-2cec844b8e63?auto=format&fit=crop&w=1200&q=90",
    notes: { top: "Citron, menthe, pamplemousse", middle: "Gingembre, jasmin, noix de muscade", base: "Santal, cedre, encens, musc" },
    isFeatured: true
  },
  {
    name: "Libre Eau de Parfum",
    brand: "Yves Saint Laurent",
    description: "Un floral moderne et lumineux qui associe lavande, fleur d'oranger et vanille pour une presence feminine affirmée.",
    purchasePrice: 650,
    quantityPurchased: 14,
    price: 1050,
    oldPrice: 1190,
    volume: "90ml",
    category: "Floral",
    gender: "Femme",
    stock: 10,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=90",
    notes: { top: "Lavande, mandarine", middle: "Fleur d'oranger, jasmin", base: "Vanille, musc, ambre" },
    isFeatured: true
  },
  {
    name: "La Vie Est Belle Eau de Parfum",
    brand: "Lancome",
    description: "Un iris gourmand solaire et enveloppant, ideal pour une vente cadeau et une clientele feminine fidele.",
    purchasePrice: 590,
    quantityPurchased: 18,
    price: 940,
    oldPrice: 1080,
    volume: "75ml",
    category: "Gourmand",
    gender: "Femme",
    stock: 13,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1585386959984-a41552231658?auto=format&fit=crop&w=1200&q=90",
    notes: { top: "Poire, cassis", middle: "Iris, jasmin, fleur d'oranger", base: "Patchouli, praline, vanille" },
    isFeatured: true
  },
  {
    name: "Baccarat Rouge 540 Eau de Parfum",
    brand: "Maison Francis Kurkdjian",
    description: "Une fragrance ambree, minerale et boisee, positionnee luxe pour panier moyen eleve et commandes speciales.",
    purchasePrice: 1450,
    quantityPurchased: 6,
    price: 2190,
    oldPrice: 0,
    volume: "70ml",
    category: "Ambre",
    gender: "Mixte",
    stock: 4,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=90",
    notes: { top: "Safran, jasmin", middle: "Ambre gris, notes minerales", base: "Cedre, bois fraichement coupe" },
    isFeatured: true
  },
  {
    name: "Oud Wood Eau de Parfum",
    brand: "Tom Ford",
    description: "Un oud sombre, doux et terreux avec une finition boisee premium pour les amateurs de parfums intenses.",
    purchasePrice: 1120,
    quantityPurchased: 7,
    price: 1690,
    oldPrice: 1890,
    volume: "100ml",
    category: "Oud",
    gender: "Mixte",
    stock: 5,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1608528577891-eb055944f2e7?auto=format&fit=crop&w=1200&q=90",
    notes: { top: "Bois de rose, cardamome", middle: "Oud, santal, vetiver", base: "Feve tonka, ambre, vanille" },
    isFeatured: true
  },
  {
    name: "Noir Imperial",
    brand: "Maison Parfumee",
    description: "Une fragrance boisee et ambree, construite pour une presence elegante et durable.",
    purchasePrice: 330,
    quantityPurchased: 18,
    price: 540,
    oldPrice: 620,
    volume: "100ml",
    category: "Boise",
    gender: "Homme",
    stock: 12,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Bergamote, poivre rose", middle: "Cedre, iris", base: "Ambre, musc, vetiver" },
    isFeatured: true
  },
  {
    name: "Rose Velours",
    brand: "Atelier Essence",
    description: "Un floral lumineux et sensuel, pense comme un voile raffine sur la peau.",
    purchasePrice: 280,
    quantityPurchased: 14,
    price: 470,
    oldPrice: 0,
    volume: "75ml",
    category: "Floral",
    gender: "Femme",
    stock: 9,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Poire, mandarine", middle: "Rose, jasmin", base: "Vanille, musc blanc" },
    isFeatured: true
  },
  {
    name: "Ambre Signature",
    brand: "Luxe Notes",
    description: "Une composition orientale chaleureuse, enveloppante et profondement elegante.",
    purchasePrice: 390,
    quantityPurchased: 10,
    price: 620,
    oldPrice: 720,
    volume: "100ml",
    category: "Oriental",
    gender: "Mixte",
    stock: 7,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Safran, cardamome", middle: "Ambre, rose noire", base: "Oud, vanille, patchouli" },
    isFeatured: true
  },
  {
    name: "Citrus Riviera",
    brand: "Maison Parfumee",
    description: "Une eau fraiche, nette et moderne, parfaite pour les journees lumineuses.",
    purchasePrice: 230,
    quantityPurchased: 20,
    price: 390,
    oldPrice: 0,
    volume: "50ml",
    category: "Frais",
    gender: "Mixte",
    stock: 15,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1619994403073-2cec844b8e63?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Citron, pamplemousse", middle: "The vert, neroli", base: "Musc, bois clair" },
    isFeatured: true
  },
  {
    name: "Oud Royal",
    brand: "Luxe Notes",
    description: "Un parfum intense et majestueux, ideal pour une signature olfactive assumee.",
    purchasePrice: 510,
    quantityPurchased: 8,
    price: 790,
    oldPrice: 890,
    volume: "100ml",
    category: "Luxe",
    gender: "Homme",
    stock: 5,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1608528577891-eb055944f2e7?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Encens, epices", middle: "Oud, cuir", base: "Ambre gris, bois precieux" },
    isFeatured: true
  },
  {
    name: "Musc Pure",
    brand: "Atelier Essence",
    description: "Une fragrance propre et douce, minimaliste, elegante et facile a porter.",
    purchasePrice: 260,
    quantityPurchased: 12,
    price: 430,
    oldPrice: 0,
    volume: "50ml",
    category: "Frais",
    gender: "Femme",
    stock: 0,
    isAvailable: false,
    image: "https://images.unsplash.com/photo-1590736704728-f4730bb30770?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Aldehydes, bergamote", middle: "Muguet, coton", base: "Musc blanc, santal" },
    isFeatured: false
  },
  {
    name: "Velvet Orchid",
    brand: "Tom Ford",
    description: "Un floral opulent et sombre, pense pour une clientele luxe qui cherche une signature sensuelle.",
    purchasePrice: 980,
    quantityPurchased: 9,
    price: 1490,
    oldPrice: 1690,
    volume: "100ml",
    category: "Floral",
    gender: "Femme",
    stock: 6,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Mandarine, miel", middle: "Orchidee, rose, jasmin", base: "Vanille, myrrhe, santal" },
    isFeatured: false
  },
  {
    name: "Acqua Mediterranea",
    brand: "Giorgio Armani",
    description: "Une fraicheur marine elegante avec agrumes, aromates et bois clairs pour une utilisation quotidienne.",
    purchasePrice: 520,
    quantityPurchased: 15,
    price: 850,
    oldPrice: 0,
    volume: "100ml",
    category: "Frais",
    gender: "Homme",
    stock: 14,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1588405748880-12d1d2a59d32?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Bergamote, citron vert", middle: "Sauge, notes marines", base: "Cedre, musc, ambre gris" },
    isFeatured: false
  },
  {
    name: "Coffret Signature Trio",
    brand: "Maison Parfumee",
    description: "Un coffret cadeau premium avec trois formats voyage pour decouvrir les signatures de la maison.",
    purchasePrice: 410,
    quantityPurchased: 20,
    price: 690,
    oldPrice: 790,
    volume: "3 x 30ml",
    category: "Coffrets",
    gender: "Mixte",
    stock: 17,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Agrumes, epices douces", middle: "Rose, jasmin, ambre", base: "Oud, musc, vanille" },
    isFeatured: true
  },
  {
    name: "Musc Tahara",
    brand: "Al Haramain",
    description: "Un musc blanc doux, propre et enveloppant, tres demande pour une routine parfumee elegante.",
    purchasePrice: 180,
    quantityPurchased: 24,
    price: 320,
    oldPrice: 390,
    volume: "50ml",
    category: "Musc",
    gender: "Mixte",
    stock: 19,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1590736704728-f4730bb30770?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Coton, aldehydes", middle: "Musc blanc, fleur propre", base: "Santal, vanille douce" },
    isFeatured: false
  },
  {
    name: "Vanille Royale",
    brand: "Montale",
    description: "Une vanille ambrée riche, gourmande et durable, ideale pour les amateurs de sillages chauds.",
    purchasePrice: 620,
    quantityPurchased: 10,
    price: 980,
    oldPrice: 1120,
    volume: "100ml",
    category: "Gourmand",
    gender: "Mixte",
    stock: 8,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1585386959984-a41552231658?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Amande, sucre brun", middle: "Vanille, benjoin", base: "Ambre, musc, bois sec" },
    isFeatured: false
  },
  {
    name: "Cuir Majeste",
    brand: "Memo Paris",
    description: "Un cuir raffine, sec et profond, positionne premium pour une clientele qui aime les parfums de caractere.",
    purchasePrice: 900,
    quantityPurchased: 7,
    price: 1390,
    oldPrice: 0,
    volume: "75ml",
    category: "Cuir",
    gender: "Mixte",
    stock: 3,
    isAvailable: true,
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=900&q=85",
    notes: { top: "Poivre rose, cardamome", middle: "Cuir, iris", base: "Patchouli, ambre, vetiver" },
    isFeatured: false
  }
];

for (const perfume of samples) {
  await Perfume.findOneAndUpdate({ name: perfume.name }, perfume, { upsert: true, new: true, setDefaultsOnInsert: true });
}

console.log(`${samples.length} sample perfumes inserted or updated.`);
process.exit(0);
